(function (root) {
  var messages = {
    'zh-CN': { search:'视频搜索', recommendations:'热门推荐', chooseSource:'选择采集站点', searchPlaceholder:'搜索你喜欢的视频...', loading:'加载中...', loadingRecommendations:'推荐内容加载中...', settings:'设置', aggregated:'聚合搜索 (所有源)', customApi:'自定义接口', recentSearches:'最近搜索', clearHistory:'清除历史', yellowFilter:'黄色内容过滤', adFilter:'分片广告过滤', about:'关于我们', privacy:'隐私政策', footer:'© 2025 剧美天下 - 自由观影，畅享精彩', playerError:'视频加载失败', tryAgain:'请尝试其他视频源或稍后重试', noEpisodes:'没有可用的集数', autoplay:'自动连播', reverseOrder:'倒序排列', sourceUnavailable:'暂无匹配视频源' },
    'zh-TW': { search:'影片搜尋', recommendations:'熱門推薦', chooseSource:'選擇影片來源', searchPlaceholder:'搜尋你喜歡的影片...', loading:'載入中...', loadingRecommendations:'推薦內容載入中...', settings:'設定', aggregated:'聚合搜尋 (所有來源)', customApi:'自訂介面', recentSearches:'最近搜尋', clearHistory:'清除歷史', yellowFilter:'成人內容過濾', adFilter:'分片廣告過濾', about:'關於我們', privacy:'隱私政策', footer:'© 2025 剧美天下 - 自由觀影，暢享精彩', playerError:'影片載入失敗', tryAgain:'請嘗試其他影片來源或稍後重試', noEpisodes:'沒有可用的集數', autoplay:'自動連播', reverseOrder:'倒序排列', sourceUnavailable:'暫無匹配影片來源' },
    en: { search:'Search videos', recommendations:'Popular', chooseSource:'Choose a video source', searchPlaceholder:'Search for a video...', loading:'Loading...', loadingRecommendations:'Loading recommendations...', settings:'Settings', aggregated:'Aggregated search (all sources)', customApi:'Custom API', recentSearches:'Recent searches', clearHistory:'Clear history', yellowFilter:'Adult content filter', adFilter:'Segment ad filter', about:'About us', privacy:'Privacy policy', footer:'© 2025 剧美天下 - Enjoy great viewing', playerError:'Video failed to load', tryAgain:'Try another source or try again later', noEpisodes:'No episodes available', autoplay:'Autoplay', reverseOrder:'Reverse order', sourceUnavailable:'No matching video sources' }
  };
  var extra = {
    recommendationDescription:'来自当前视频源的最新内容', recommendationLoading:'推荐内容加载中...', customApiDescription:'自定义接口地址（可添加多个，用逗号分隔）',
    yellowFilterDescription:'过滤分类包含成人内容', adFilterDescription:'关闭可减少旧版浏览器播放卡顿问题', sourceStatus:'源状态', sourceHealthy:'可用',
    playerLoading:'正在加载视频...', previousEpisode:'上一集', nextEpisode:'下一集', episodeList:'选集', shortcutHint:'键盘快捷键',
    networkError:'网络连接错误，请检查网络设置', timeoutError:'请求超时，服务器响应时间过长', apiError:'API接口返回错误，请尝试更换数据源', unknownError:'发生未知错误，请刷新页面重试',
    backHome:'回到首页', privacyLocalStorage:'浏览器本地存储', privacyAds:'第三方广告与统计', privacyVideoServices:'视频接口与外部服务', privacyChoices:'您的选择', privacyUpdates:'政策更新'
  };
  Object.keys(messages).forEach(function(locale){ Object.keys(extra).forEach(function(key){ if (!messages[locale][key]) messages[locale][key] = extra[key]; }); });
  Object.assign(messages['zh-TW'], { recommendationDescription:'來自目前影片來源的最新內容', customApiDescription:'自訂介面地址（可添加多個，用逗號分隔）', sourceStatus:'來源狀態', sourceHealthy:'可用', playerLoading:'正在載入影片...', previousEpisode:'上一集', nextEpisode:'下一集', episodeList:'選集', backHome:'回到首頁', privacyLocalStorage:'瀏覽器本地儲存', privacyAds:'第三方廣告與統計', privacyVideoServices:'影片介面與外部服務', privacyChoices:'您的選擇', privacyUpdates:'政策更新' });
  Object.assign(messages.en, { recommendationDescription:'Latest content from the current source', customApiDescription:'Custom API address (comma-separated)', yellowFilterDescription:'Filter adult content categories', adFilterDescription:'Disable to reduce playback lag on older browsers', sourceStatus:'Source status', sourceHealthy:'Available', playerLoading:'Loading video...', previousEpisode:'Previous episode', nextEpisode:'Next episode', episodeList:'Episodes', shortcutHint:'Keyboard shortcuts', networkError:'Network error', timeoutError:'Request timed out', apiError:'API error', unknownError:'Unknown error', backHome:'Back home', privacyLocalStorage:'Browser local storage', privacyAds:'Third-party advertising and analytics', privacyVideoServices:'Video APIs and external services', privacyChoices:'Your choices', privacyUpdates:'Policy updates' });
  root.SUPPORTED_LOCALES=['zh-CN','zh-TW','en']; root.LOCALE_LABELS={'zh-CN':'简体中文','zh-TW':'繁體中文',en:'English'}; root.MESSAGES=messages;
})(globalThis);
