(function (root) {
  var messages = {
    'zh-CN': { openSettings:'打开设置', closeSettings:'关闭设置', closeModal:'关闭详情', language:'语言', region:'地区', sourceMode:'来源模式', regionalRecommendation:'使用区域推荐', manualSource:'手动选择来源', search:'视频搜索', searchButton:'搜索', recommendations:'热门推荐', chooseSource:'选择采集站点', searchPlaceholder:'搜索你喜欢的视频...', loading:'加载中...', loadingRecommendations:'推荐内容加载中...', settings:'设置', aggregated:'聚合搜索（所有源）', customApi:'自定义接口', customApiLabel:'自定义接口地址（可添加多个，用逗号分隔）', customApiPlaceholder:'https://example1.com,https://example2.com...', recentSearches:'最近搜索记录', clearHistory:'清除搜索历史', yellowFilter:'黄色内容过滤', yellowFilterDescription:'过滤分类包含成人内容的视频', adFilter:'分片广告过滤', adFilterDescription:'关闭可减少旧版浏览器播放卡顿问题', currentSourceCode:'当前站点代码：', slogan:'自由观影，畅享精彩', changeBatch:'换一批', disclaimer:'免责声明：本站仅为视频搜索工具，不存储、上传或分发任何视频内容。所有视频均来自第三方API接口。如有侵权，请联系相关内容提供方。', ad:'广告', juicyAd:'JuicyAds 广告', nativeAd:'原生广告', about:'关于我们', privacy:'隐私政策', footer:'© 2025 剧美天下 - 自由观影，畅享精彩', playerError:'视频加载失败', tryAgain:'请尝试其他视频源或稍后重试', noEpisodes:'没有可用的集数', autoplay:'自动连播', reverseOrder:'倒序排列', sourceUnavailable:'暂无匹配视频源' },
    'zh-TW': { openSettings:'開啟設定', closeSettings:'關閉設定', closeModal:'關閉詳情', language:'語言', region:'地區', sourceMode:'來源模式', regionalRecommendation:'使用區域推薦', manualSource:'手動選擇來源', search:'影片搜尋', searchButton:'搜尋', recommendations:'熱門推薦', chooseSource:'選擇影片來源', searchPlaceholder:'搜尋你喜歡的影片...', loading:'載入中...', loadingRecommendations:'推薦內容載入中...', settings:'設定', aggregated:'聚合搜尋（所有來源）', customApi:'自訂介面', customApiLabel:'自訂介面地址（可添加多個，用逗號分隔）', customApiPlaceholder:'https://example1.com,https://example2.com...', recentSearches:'最近搜尋記錄', clearHistory:'清除搜尋歷史', yellowFilter:'成人內容過濾', yellowFilterDescription:'過濾包含成人內容分類的影片', adFilter:'分片廣告過濾', adFilterDescription:'關閉可減少舊版瀏覽器播放卡頓問題', currentSourceCode:'目前來源代碼：', slogan:'自由觀影，暢享精彩', changeBatch:'換一批', disclaimer:'免責聲明：本站僅為影片搜尋工具，不儲存、上傳或分發任何影片內容。所有影片均來自第三方介面。如有侵權，請聯絡相關內容提供方。', ad:'廣告', juicyAd:'JuicyAds 廣告', nativeAd:'原生廣告', about:'關於我們', privacy:'隱私政策', footer:'© 2025 剧美天下－自由觀影，暢享精彩', playerError:'影片載入失敗', tryAgain:'請嘗試其他影片來源或稍後重試', noEpisodes:'沒有可用的集數', autoplay:'自動連播', reverseOrder:'倒序排列', sourceUnavailable:'暫無匹配影片來源' },
    en: { openSettings:'Open settings', closeSettings:'Close settings', closeModal:'Close dialog', language:'Language', region:'Region', sourceMode:'Source mode', regionalRecommendation:'Use regional recommendation', manualSource:'Manual source', search:'Search videos', searchButton:'Search', recommendations:'Popular', chooseSource:'Choose a video source', searchPlaceholder:'Search for a video...', loading:'Loading...', loadingRecommendations:'Loading recommendations...', settings:'Settings', aggregated:'Aggregated search (all sources)', customApi:'Custom API', customApiLabel:'Custom API address (comma-separated)', customApiPlaceholder:'https://example1.com,https://example2.com...', recentSearches:'Recent searches', clearHistory:'Clear search history', yellowFilter:'Adult content filter', yellowFilterDescription:'Filter videos in adult categories', adFilter:'Segment ad filter', adFilterDescription:'Disable to reduce playback lag on older browsers', currentSourceCode:'Current source code:', slogan:'Enjoy great viewing', changeBatch:'Change batch', disclaimer:'Disclaimer: This site is a video search tool and does not store, upload, or distribute video content. Videos come from third-party APIs.', ad:'Advertisement', juicyAd:'JuicyAds advertisement', nativeAd:'Native advertisement', about:'About us', privacy:'Privacy policy', footer:'© 2025 剧美天下 - Enjoy great viewing', playerError:'Video failed to load', tryAgain:'Try another source or try again later', noEpisodes:'No episodes available', autoplay:'Autoplay', reverseOrder:'Reverse order', sourceUnavailable:'No matching video sources' }
  };
  var extra = {
    siteTitle:'Video search - 剧美天下', siteDescription:'Search and watch videos from multiple sources without registration.',
    routeStatus:'Route status', fallback:'Using fallback sources', legacyCache:'Legacy cache', recommendationDescription:'Latest content from the current video sources', recommendationLoading:'Loading recommendations...', recommendationError:'Recommendations unavailable. Please try again later.', noRecommendations:'No recommendations available.', customApiDescription:'Custom API address (comma-separated)',
    yellowFilterDescription:'过滤分类包含成人内容', adFilterDescription:'关闭可减少旧版浏览器播放卡顿问题', sourceStatus:'源状态', sourceHealthy:'可用',
    playerLoading:'正在加载视频...', previousEpisode:'上一集', nextEpisode:'下一集', episodeList:'选集', shortcutHint:'键盘快捷键',
    networkError:'网络连接错误，请检查网络设置', timeoutError:'请求超时，服务器响应时间过长', apiError:'API接口返回错误，请尝试更换数据源', unknownError:'发生未知错误，请刷新页面重试',
    backHome:'回到首页', privacyLocalStorage:'浏览器本地存储', privacyAds:'第三方广告与统计', privacyVideoServices:'视频接口与外部服务', privacyChoices:'您的选择', privacyUpdates:'政策更新'
  };
  Object.keys(messages).forEach(function(locale){ Object.keys(extra).forEach(function(key){ if (!messages[locale][key]) messages[locale][key] = extra[key]; }); });
  Object.assign(messages['zh-CN'], { routeStatus:'路由状态', fallback:'已使用备用来源', legacyCache:'旧版缓存', recommendationDescription:'来自当前视频源的最新内容', recommendationError:'暂时无法加载推荐内容，请稍后重试', noRecommendations:'暂无推荐内容', customApiDescription:'自定义接口地址（可添加多个，用逗号分隔）' });
  Object.assign(messages['zh-TW'], { routeStatus:'路由狀態', fallback:'已使用備用來源', legacyCache:'舊版快取', recommendationDescription:'來自目前影片來源的最新內容', recommendationError:'暫時無法載入推薦內容，請稍後再試', noRecommendations:'暫無推薦內容', customApiDescription:'自訂介面地址（可添加多個，用逗號分隔）', sourceStatus:'來源狀態', sourceHealthy:'可用', playerLoading:'正在載入影片...', previousEpisode:'上一集', nextEpisode:'下一集', episodeList:'選集', backHome:'回到首頁', privacyLocalStorage:'瀏覽器本地儲存', privacyAds:'第三方廣告與統計', privacyVideoServices:'影片介面與外部服務', privacyChoices:'您的選擇', privacyUpdates:'政策更新' });
  Object.assign(messages.en, { legacyCache:'Legacy cache', recommendationDescription:'Latest content from the current source', customApiDescription:'Custom API address (comma-separated)', yellowFilterDescription:'Filter adult content categories', adFilterDescription:'Disable to reduce playback lag on older browsers', sourceStatus:'Source status', sourceHealthy:'Available', playerLoading:'Loading video...', previousEpisode:'Previous episode', nextEpisode:'Next episode', episodeList:'Episodes', shortcutHint:'Keyboard shortcuts', networkError:'Network error', timeoutError:'Request timed out', apiError:'API error', unknownError:'Unknown error', backHome:'Back home', privacyLocalStorage:'Browser local storage', privacyAds:'Third-party advertising and analytics', privacyVideoServices:'Video APIs and external services', privacyChoices:'Your choices', privacyUpdates:'Policy updates', aboutIntro:'The project source code is hosted on GitHub. Visit our repository:', aboutMission:'剧美天下 is a free video search platform offering search and playback services.', privacyIntro:'剧美天下 is a registration-free video search and playback page. This policy explains how page scripts, third-party video APIs, and advertising services may process information.', privacyStorageText:'Language, region, source mode, source preferences, recent searches, and playback settings may be stored in browser localStorage. They remain on your device and are not uploaded by this site.', privacyAdsText:'We use JuicyAds and Adsterra advertising. Their scripts or iframes may process IP address, device and browser details, referrer, impressions, and clicks under their own privacy policies.', privacyVideoText:'Search and playback data come from third-party public APIs and external players. Those providers may log requests according to their policies.', privacyChoicesText:'You can block or delete cookies, clear this site’s local storage, or use ad-blocking tools.', privacyUpdatesText:'We will update this page when advertising services, video APIs, or page features change.' });
  Object.assign(messages['zh-CN'], { siteTitle:'视频搜索 - 剧美天下', siteDescription:'搜索并观看来自多个视频源的内容，无需注册即可使用。' });
  Object.assign(messages['zh-TW'], { siteTitle:'影片搜尋 - 剧美天下', siteDescription:'搜尋並觀看來自多個影片來源的內容，無需註冊即可使用。' });
  Object.assign(messages.en, { siteTitle:'Video search - 剧美天下', siteDescription:'Search and watch videos from multiple sources without registration.' });
  Object.assign(messages['zh-CN'], { forwardOrder:'正序排列', sourceError:'当前视频源加载失败', playerTitle:'播放器', invalidVideoUrl:'视频链接无效，请尝试其他视频源', parseVideoError:'视频链接解析失败，请尝试其他视频源', playbackError:'视频播放失败，请检查当前视频源或尝试其他来源', slowLoading:'视频源加载时间较长，请耐心等待；如无响应请尝试其他视频源' });
  Object.assign(messages['zh-TW'], { forwardOrder:'正序排列', sourceError:'目前影片來源載入失敗', playerTitle:'播放器', invalidVideoUrl:'影片連結無效，請嘗試其他影片來源', parseVideoError:'影片連結解析失敗，請嘗試其他影片來源', playbackError:'影片播放失敗，請檢查目前影片來源或嘗試其他來源', slowLoading:'影片來源載入時間較長，請耐心等待；如無回應請嘗試其他影片來源' });
  Object.assign(messages.en, { forwardOrder:'Forward order', sourceError:'The selected video source failed to load', playerTitle:'Player', invalidVideoUrl:'Invalid video link; try another source', parseVideoError:'Video link parsing failed; try another source', playbackError:'Playback failed; check the current source or try another source', slowLoading:'The video source is taking longer to load; try another source if it does not respond' });
  var dynamic = {
    'zh-CN': { searchPrompt:'请输入搜索内容', searchEmpty:'没有找到匹配的结果', searchEmptyHint:'请尝试其他关键词或更换数据源', searchError:'搜索请求失败，请稍后重试', searchTimeout:'搜索请求超时，请检查网络连接', clickToPlay:'点击播放', unknownVideo:'未知视频', videoCover:'视频封面', noCover:'无封面', viewDetails:'点击查看详情', noDescription:'暂无介绍', invalidVideoId:'视频ID无效', customApiRequired:'请先设置自定义API地址', customApiUnavailable:'无可用的自定义API', noPlayableVideo:'没有找到可播放的视频', invalidVideoLink:'无效的视频链接', playbackLoadError:'视频播放加载失败，请尝试其他视频源', detailTimeout:'获取详情超时，请检查网络连接', detailError:'获取详情失败，请稍后重试', episodeNumber:'第{number}集', noEpisodeInfo:'无集数信息', siteTesting:'测试中...', sitePendingTest:'待测试', featuredRecommendation:'精彩推荐', customApiUnset:'未设置API', allSourcesUnavailable:'全部不可用', testingSite:'正在测试站点可用性...', testingCustomApi:'正在测试API可用性...', validCustomApiRequired:'请输入至少一个有效的API地址', loadingTimeout:'操作超时，请稍后重试', recentSearchesLabel:'最近搜索:', searchedAt:'搜索于: {date}', searchHistoryCleared:'搜索历史已清除', searchHistoryClearError:'清除搜索历史失败', noEligibleSources:'当前地区/语言没有可用的视频源', adLabel:'广告' },
    'zh-TW': { searchPrompt:'請輸入搜尋內容', searchEmpty:'沒有找到匹配的結果', searchEmptyHint:'請嘗試其他關鍵字或更換來源', searchError:'搜尋請求失敗，請稍後再試', searchTimeout:'搜尋請求逾時，請檢查網路連線', clickToPlay:'點擊播放', unknownVideo:'未知影片', videoCover:'影片封面', noCover:'無封面', viewDetails:'點擊查看詳情', noDescription:'暫無介紹', invalidVideoId:'影片 ID 無效', customApiRequired:'請先設定自訂介面地址', customApiUnavailable:'沒有可用的自訂介面', noPlayableVideo:'沒有找到可播放的影片', invalidVideoLink:'無效的影片連結', playbackLoadError:'影片載入失敗，請嘗試其他影片來源', detailTimeout:'取得詳情逾時，請檢查網路連線', detailError:'取得詳情失敗，請稍後再試', episodeNumber:'第{number}集', noEpisodeInfo:'無集數資訊', siteTesting:'測試中...', sitePendingTest:'待測試', featuredRecommendation:'精彩推薦', customApiUnset:'尚未設定介面', allSourcesUnavailable:'全部不可用', testingSite:'正在測試來源可用性...', testingCustomApi:'正在測試介面可用性...', validCustomApiRequired:'請輸入至少一個有效的介面地址', loadingTimeout:'操作逾時，請稍後再試', recentSearchesLabel:'最近搜尋:', searchedAt:'搜尋於: {date}', searchHistoryCleared:'搜尋記錄已清除', searchHistoryClearError:'清除搜尋記錄失敗', noEligibleSources:'目前地區/語言沒有可用的影片來源', adLabel:'廣告' },
    en: { searchPrompt:'Please enter a search term', searchEmpty:'No matching results', searchEmptyHint:'Try another keyword or video source', searchError:'Search request failed; please try again', searchTimeout:'Search request timed out; check your connection', clickToPlay:'Play', unknownVideo:'Unknown video', videoCover:'Video cover', noCover:'No cover', viewDetails:'View details', noDescription:'No description', invalidVideoId:'Invalid video ID', customApiRequired:'Please set a custom API address first', customApiUnavailable:'No custom API available', noPlayableVideo:'No playable video found', invalidVideoLink:'Invalid video link', playbackLoadError:'Video failed to load; try another source', detailTimeout:'Loading details timed out', detailError:'Failed to load details', episodeNumber:'Episode {number}', noEpisodeInfo:'No episode information', siteTesting:'Testing...', sitePendingTest:'Pending test', featuredRecommendation:'Featured', customApiUnset:'API not configured', allSourcesUnavailable:'All unavailable', testingSite:'Testing source availability...', testingCustomApi:'Testing API availability...', validCustomApiRequired:'Enter at least one valid API address', loadingTimeout:'Operation timed out; please try again', recentSearchesLabel:'Recent searches:', searchedAt:'Searched at: {date}', searchHistoryCleared:'Search history cleared', searchHistoryClearError:'Failed to clear search history', noEligibleSources:'No eligible video sources for this region or language', adLabel:'Advertisement' }
  };
  Object.keys(dynamic).forEach(function(locale){ Object.assign(messages[locale], dynamic[locale]); });
  Object.assign(messages['zh-CN'], { aboutIntro:'本项目代码托管在 GitHub 上，欢迎访问我们的仓库：', aboutMission:'剧美天下是一个免费的在线视频搜索平台，提供视频搜索和播放服务。', privacyIntro:'剧美天下是一个无需注册的在线视频搜索与观看页面。本政策说明页面脚本、第三方视频接口和广告服务可能处理哪些信息。', privacyStorageText:'语言、地区、来源模式、来源偏好、最近搜索和播放设置可能保存在浏览器 localStorage（本地存储）中。这些信息仅保留在您的设备上，不会由本站上传。', privacyAdsText:'本站接入 JuicyAds 和 Adsterra 广告。其脚本或 iframe 可能按照各自政策处理 IP、设备、浏览器、来源页及广告展示与点击信息。', privacyVideoText:'搜索和播放数据来自第三方公开接口及外部播放器，相关服务商可能按照自己的政策记录请求。', privacyChoicesText:'您可以阻止或删除 Cookie、清除本站本地存储，或使用广告拦截工具。', privacyUpdatesText:'广告服务、视频接口或页面功能发生变化时，我们会更新本页面。' });
  Object.assign(messages['zh-TW'], { aboutIntro:'本專案程式碼託管於 GitHub，歡迎造訪我們的儲存庫：', aboutMission:'剧美天下是免費的影片搜尋平台，提供影片搜尋與播放服務。', privacyIntro:'剧美天下是無需註冊的影片搜尋與觀看頁面。本政策說明頁面腳本、第三方影片介面和廣告服務可能處理哪些資訊。', privacyStorageText:'語言、地區、來源模式、來源偏好、最近搜尋與播放設定可能儲存在瀏覽器 localStorage（本地儲存）中。這些資訊僅保留在您的裝置上，不會由本站上傳。', privacyAdsText:'本站接入 JuicyAds 和 Adsterra 廣告。其腳本或 iframe 可能依各自政策處理 IP、裝置、瀏覽器、來源頁及廣告展示與點擊資訊。', privacyVideoText:'搜尋與播放資料來自第三方公開介面及外部播放器，相關服務商可能依其政策記錄請求。', privacyChoicesText:'您可以阻擋或刪除 Cookie、清除本站本地儲存，或使用廣告封鎖工具。', privacyUpdatesText:'廣告服務、影片介面或頁面功能變更時，我們會更新本頁面。' });
  root.SUPPORTED_LOCALES=['zh-CN','zh-TW','en']; root.LOCALE_LABELS={'zh-CN':'简体中文','zh-TW':'繁體中文',en:'English'}; root.MESSAGES=messages;
})(globalThis);
